export const GET_UPCOMING_LAUNCHES_REQUEST = 'GET_UPCOMING_LAUNCHES_REQUEST';
export const GET_UPCOMING_LAUNCHES_SUCCESS = 'GET_UPCOMING_LAUNCHES_SUCCESS';
export const GET_UPCOMING_LAUNCHES_FAIL = 'GET_UPCOMING_LAUNCHES_FAIL';
